### ISSUE TITLE
Chrome with MT fixed and COEP/COOP server!

### ISSUE THREAD

**Issue by radames** [antiboredom/ffmpeg-explorer#13]
Hi @antiboredom, amazing project! 
It looks like the issue with ffmpeg wasm MT on Chrome was solved with the latest `@ffmpeg/ffmpeg@0.12.6` it worth trying!

https://github.com/antiboredom/ffmpeg-explorer/blob/568390ba23b5565dd5ce623eed1d22ea4c7b3b85/src/App.svelte#L21-L22

BTW is you ever need to host static pages with COEP/COOP header HuggingFace Static SDK now support custom headers!!
https://huggingface.co/spaces/radames/OpenAI-CLIP-JavaScript
```
# README.md
custom_headers:
  cross-origin-embedder-policy: require-corp
  cross-origin-opener-policy: same-origin
  cross-origin-resource-policy: cross-origin
```
docs: https://huggingface.co/docs/hub/spaces-config-reference#:~:text=can%20be%20embedded.-,custom_headers,-%3A%20Dict%5Bstring
ps. I work there 🤦🏼
